rails/cssbundling-rails

README.md

Same as https://github.com/rails/jsbundling-rails/pull/9
`set-script` was not part of `npx` until version 7.1.0 (https://github.com/npm/cli/releases/tag/v7.1.0) released December 2020.

Mention required npx version in readme

---

lib/install/install.rb

Right now the whole `builds` folder is ignored so bundling on production will fail with error:
> Sprockets::ArgumentError: link_tree argument must be a directory

Exclude .keep file from .gitignore

---

lib/install/install.rb

Currently `bin/dev` is not copied as an executable file. This change makes it executable.
This change mirrors the same code in https://github.com/rails/jsbundling-rails/blob/main/lib/install/install.rb

Ensure bin/dev is executable

---

README.md
lib/tasks/cssbundling/build.rake

Don't fail build task when test:prepare isn't defined, as described here: https://github.com/rails/jsbundling-rails/issues/10

Don't enhance test:prepare unless it exists

---

lib/install/sass/install.rb

I ran into an issue when trialing the new gem, whereby `@import` statements wouldn't load common Sass libraries without specifying the full path to the `node_modules` directory.
This allows simple imports such as `@import 'glidecss/base';` to work with the default install.

Allow imports from node modules with default install

---

lib/tasks/cssbundling/build.rake

The rake to prepare rails test in Rails 6 (and below) is `bin/rails db:test:prepare`.

Fallback to `db:test:prepare` when `test:prepare` rake is not found

---

lib/install/install.rb

To avoid error:
> Sprockets::ArgumentError: link_tree argument must be a directory.
This should add the pattern like this:
```
/app/assets/builds/*
!/app/assets/builds/.keep
```
The same pattern as the one in default .gitignore file generated by 
rails:
```
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep
```

Fix `Sprockets::ArgumentError` during deployment

---

lib/install/install.rb

In an application with an existing `Procfile.dev`, the `css: yarn build:css --watch` is not appended on a new line. Adding `\n` adds the build command on a new line and avoid errors such as `| unknown command: ./bin/webpack-dev-servercss: yarn build:css --watch`

procfile append :css on new line

---

lib/install/install.rb

I think this is useful for people who are migrating from `webpacker` and was using `stylesheet_pack_tag` instead of `stylesheet_link_tag`.
Similar to [jsbundling-rails](https://github.com/rails/jsbundling-rails/blob/c7f8f8564436de9529250ef6bbd511568ca6339d/lib/install/install.rb#L10).

Add stylesheet link tag in application layout

---

lib/install/install.rb

This will add `/node_modules` to `.gitignore` and also add a new line before `/app/assets/builds/*`.
Before:
```
...
/config/master.key
/app/assets/builds/*
!/app/assets/builds/.keep
```
After:
```
...
/config/master.key
/app/assets/builds/*
!/app/assets/builds/.keep
/node_modules
```
I separated the commands to make sure we don't append `/node_modules` twice.

Ignore node_modules

---

lib/install/install.rb

Before:
```
//= link_tree ../images
//= link_tree ../../javascript .js
//= link_tree ../builds
```
After:
```
//= link_tree ../images
//= link_tree ../../javascript .js
//= link_tree ../builds
```

Don't keep empty line after removing `link_directory`

---

README.md
lib/install/bulma/application.bulma.scss
lib/install/bulma/install.rb
lib/tasks/cssbundling/install.rake

Hi! I added Bulma CSS support to cssbundling-rails gem. I'm not sure if this is the correct way to do it, but it works on my machine, I just followed the way how bootstrap was added to it.
And [here is a clean "rails _7.0.0.alpha2_ new" repo I used to test my implementation](https://github.com/printfinn/cssbundling-bulma-test).
I don't know why `node_modules` dir is not in the `.gitignore` file by default in rails 7, so I also committed it with an additional commit to this repo (6MB dir size) in case someone needs to see it.

Add bulma support

---

lib/install/install.rb

Fixed contents of `Procfile.dev` generated when executing `rails new new_app -j esbuild --css tailwind`.
before(without newline terminated):
```
web: bin/rails server -p 3000
js: yarn build --watch
css: yarn build:css --watch
```
after(with newline terminated):
```
web: bin/rails server -p 3000
js: yarn build --watch
css: yarn build:css --watch
```

Fixed Procfile.dev to remove unnecessary empty line and terminated with a newline

---

lib/install/postcss/install.rb
lib/install/postcss/postcss.config.js

This replaces `postcss-preset-env` with `postcss-nesting` and `autoprefixer` to resolve a dependency issue and improve build speed.
Closes #29

Replace postcss-preset-env

---

lib/install/install.rb
lib/tasks/cssbundling/build.rake

Fixes #28 
I’m not sure convention wise if there are better ways of outputting this error message, let me know and I can make adjustments. 
Once sorted I’ll PR a similar change into jsbundling-rails.

If build command fails raise a helpful exception

---

lib/tasks/cssbundling/build.rake

This PR makes `css:build` depend on `yarn:install` directly instead of running `yarn install` on its own. This ensures `yarn install` is only run once and not multiple times.
Comparable to rails/jsbundling-rails#43 and rails/jsbundling-rails#49.
**This relies on rails/rails#43641** which corrects `yarn:install` to use `yarn` via the PATH and not require `bin/yarn`, which is no longer added in Rails 7.
I believe it's safe to depend on yarn:install directly because cssbundling-rails already depends on railties, so yarn:install should always be available. If this somehow isn't valid, then we could add a no-op version of yarn:install here which would at least avoid errors while also not skipping enhancement as the existing approach does.

Make css:build depend on yarn:install directly

---

lib/tasks/cssbundling/clobber.rake

https://github.com/rails/jsbundling-rails/pull/52#issuecomment-971580290

Enhance assets:clobber with css:clobber

---

lib/install/tailwind/tailwind.config.js

The `css:install:tailwind` task simply installs the latest version of Tailwind. The new major release of Tailwind has changed from using `purge` to `content`.
We are getting warning if we don't update:
```
warn - The `purge`/`content` options have changed in Tailwind CSS v3.0.
warn - Update your configuration file to eliminate this warning.       
```
Reference:
- [Tailwind 3.0 blog post](https://www.themes.dev/blog/tailwind-css-version-3/#purge-needs-to-be-renamed-to-content)

Update default tailwind.config.js for Tailwind 3

---

lib/install/dev

This tiny change allows passing foreman options when running `bin/dev`. The most common use case is excluding some processes (eg `web` or `worker`) when you want to debug them:
```
bin/dev all=1,web=0
```

Bypass CLI options to Foreman in bin/dev

---

lib/tasks/cssbundling/build.rake

a749ca2 suggests that "Sprockets is not a dependency", so we should not
assume that the assets:precompile task will be defined. If it's not
there, we should just skip enhancing it.
Fixes #58

Check assets:precompile is defined before enhancing

---

README.md

When a user invokes `rails test` or uses a test framework that does not define a `test:prepare` Rake task, `css:build` must be run manually. This is already documented in the README.
If `jsbundling-rails` is also being used, `javascript:build` may also need to be run (ie, esbuild + tailwind). 
If either `css:build` or `javascript:build` is required and is not run, minitest reports the same error:
> ActionView::Template::Error: The asset "application.css" is not present in the asset pipeline.
This PR aims to improve the documentation to avoid others chasing their tail for a few hours like I did.

README clarify javascript:build may also need to be run if test:prepare is not defined

---

lib/install/bootstrap/install.rb
lib/install/bulma/install.rb
lib/install/postcss/install.rb
lib/install/sass/install.rb
lib/install/tailwind/install.rb

This makes it more clear what needs to be done.
It is based on the discussion in https://github.com/rails/cssbundling-rails/issues/65

Make the message for adding build:css to package.json more visible if npx version is < 7.1

---

lib/tasks/cssbundling/clobber.rake

https://github.com/rails/cssbundling-rails/commit/a749ca29a91ee0b5cbc884b02505631576b09e43 suggests that "Sprockets is not a dependency", so we should not
assume that the assets:precompile AND assets:clobber tasks will be defined. If it's not
there, we should just skip enhancing it.
Related to: https://github.com/rails/cssbundling-rails/pull/59
Fixes issue `Don't know how to build task 'assets:clobber'`
cc @dhh @richardTowers

Check assets:clobber is defined before enhancing

---

lib/install/bootstrap/application.bootstrap.scss
lib/install/bootstrap/install.rb

Closes #63 
Adds Bootstrap Icons to Bootstrap install task, which helps start with Bootstrap 5 and Bootstrap Icons as quickly as possible.

Install bootstrap-icons along with bootstrap

---

lib/install/tailwind/tailwind.config.js

Hi,
While using Rails 7.0.0 with Tailwind I noticed that if I changed my `application.tailwind.css` file, such as adding these lines at the bottom:
```css
body {
background-color: #00ff00;
}
```
The tailwindcss watcher wasn't picking up the change and it did not produce a new build.
After applying this PR's patch it picks up the changes and it does produce a new build.

Add stylesheets path to TailwindCSS' content list

---

lib/install/bootstrap/install.rb
lib/install/bulma/install.rb
lib/install/sass/install.rb

So the sass cli allows for multiple sources & outputs, just not using the space syntax. Using the `source:destination` syntax makes this more obvious if a user wanted to bundle multiple sources at once they can just append another into this list.
I'm not sure if this is possible with postcss and tailwind CLIs, if these can be updated as well that'd be great

Change sass cli params to permit multiple build sources

---

lib/install/dev

Per #87:
Because `rbenv` uses shims, the existence of `foreman` in any gemset will result in this test passing (indicating that the tool is available), whether it's in the current gemset or not.
This test, courtesy of @t27duck, ensures that `foreman` is actually operable in the current context.

Fix for foreman existence test in rbenv installs.

---

lib/install/dev

Hi,
I know this does not solve any current problem, but maybe would be better to use the command [`gem list`](https://guides.rubygems.org/command-reference/#gem-list) to check for foreman.  This command gives a better output (boolean) and appropriate exit code.
Thanks
Related with rails/cssbundling-rails/pull/91

Use ruby command "gem list" for foreman existence test

---

lib/install/dev

This fixes a couple issues we ran into, using small alpine ruby image under docker, developing locally with docker compose:
1. use `exec` to invoke `foreman`. This ensures the `dev` script is replaced by the `foreman` process and  signals/interrupts like <kbd>ctrl</kbd>+<kbd>c</kbd> are handled correctly. Without this, the child `foreman` processes are not stopped gracefully and the PID file not cleaned up.
2. replace `bash` with `sh`. Alpine Linux (for example) ships with `ash` (not `bash`) but includes `sh`, so this seems like a reasonable choice as "lowest common denominator"
---
Gist of minimal test case:
https://gist.github.com/defeated/5d1b7469d5fedb6d6b242f141c68c895

Minor portability improvements to ./bin/dev

---

lib/install/Procfile.dev

Foreman sets the PORT environment variable to 5000 by default
See https://github.com/rails/jsbundling-rails/pull/111

Instead of forcing a port in Procfile, unset Foremans's PORT

---

lib/tasks/cssbundling/build.rake

Hello,
I was playing with a dockerfile like this:
```dockerfile
FROM node:18-alpine as builder
WORKDIR /src
COPY package.json /src
COPY yarn.lock /src
RUN yarn install
COPY . /src
RUN yarn build:css
FROM ruby:3.0.4
WORKDIR /src
COPY Gemfile .
COPY Gemfile.lock .
RUN bundle install
COPY . .
COPY --from=builder /src/app/assets/builds/application.css /src/app/assets/builds/
RUN bundle exec rails assets:precompile
EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
```
And I was getting this error:
```
Step 16/18 : RUN bundle exec rails assets:precompile
---> Running in b268b243b355
sh: 1: yarn: not found
rails aborted!
cssbundling-rails: Command css:build failed, ensure yarn is installed and `yarn build:css` runs without errors or add SKIP_YARN
Tasks: TOP => …
```

Add possibility to skip css:build during assets:precompile

---

lib/tasks/cssbundling/clobber.rake

Right now, the `CSS:clobber` task **only** removes `.css` files, leaving any sourcemap present in the directory if present.
This change mimics how [jsbundling-rails](https://github.com/rails/jsbundling-rails/blob/main/lib/tasks/jsbundling/clobber.rake#L4) works, and removes both CSS files and sourcemaps from the directory.

Update css:clobber to also remove sourcemaps

---

lib/tasks/cssbundling/build.rake

https://github.com/rails/jsbundling-rails/pull/128
Both gems should have same logic.

Enhance spec:prepare command with CSS build

---

lib/install/Procfile.dev
lib/install/dev

With this configuration `bin/dev` will use port 3000, but `bin/dev -p 3001` will correctly start the server on port 3001.
Cross-posted from https://github.com/rails/jsbundling-rails/pull/148.

Default to port 3000 while allowing override

---

lib/tasks/cssbundling/build.rake

Similar to rails/jsbundling-rails#150

Support environment variable to skip Yarn install

---

lib/install/postcss/install.rb
lib/install/postcss/postcss.config.js

https://github.com/postcss/postcss-import
It felt natural to me to immediately use the @import directive right after installing PostCSS and after fighting a bit with it I realised the plugin wasn't installed so it seemed like it would be a sensible default to have.
Adding the official postcss-import plugin enables the usage of PostCSS's @import directive out of the box so when adding a CSS library (like open-props) or when adding custom stylesheets it works seamlessly.
From the PostCSS-import docs:
> [PostCSS](https://github.com/postcss/postcss) plugin to transform @import rules by inlining content.
This plugin can consume local files, node modules or web_modules. To resolve path of an @import rule, it can look into root directory (by default process.cwd()), web_modules, node_modules or …

Add PostCSS import plugin as default

---

lib/tasks/cssbundling/build.rake

Methods defined in Rake files are added to the global namespace. This means `cssbundling-rails` and `jsbundling-rails` using the same `build_command` method name get overridden by one or the other.
This introduces a module to namespace these methods and provides a place for any future methods to be defined. 
Since these only apply to the tasks in `build.rake`, I just defined the module there, but we could extract it to a file and require it instead.
Fixes #131
cc @terracatta

Namespace helper methods for css:build command

---

lib/install/install.rb

Fixes #133.
This was a really silly mistake. 
I forgot to add the file extensions to the file names when switching between bun and node. This is a code path I didn't manually test as I did all my testing in a repo that previously had the jsbundling-rails installer on it (so I always had a Procfile).
```
☁  jason_test_css [main] ⚡  ls Procfile.dev
ls: Procfile.dev: No such file or directory
☁  jason_test_css [main] ⚡  ./bin/rails css:install:bootstrap
apply  /Users/jmeller/code/terracatta/cssbundling-rails/lib/install/install.rb
Build into app/assets/builds
create    app/assets/builds
create    app/assets/builds/.keep
append    app/assets/config/manifest.js
Stop linking stylesheets automatically
gsub    app/assets/config/manifest.js
append    .gitignore
append    .gitignore
Remove …
```

Fix missing extensions on Procfile generation

---

lib/install/bootstrap/install.rb

Fixes error on creation of a new app using -css bootstrap flag or ./bin/rails css:install:bootstrap
**Rails output before this fix**
```
Build into app/assets/builds
exist  app/assets/builds
identical  app/assets/builds/.keep
File unchanged! Either the supplied flag value not found or the content has already been inserted!  app/assets/config/manifest.js
Stop linking stylesheets automatically
gsub  app/assets/config/manifest.js
File unchanged! Either the supplied flag value not found or the content has already been inserted!  .gitignore
File unchanged! Either the supplied flag value not found or the content has already been inserted!  .gitignore
Remove app/assets/stylesheets/application.css so build output can take over
remove  app/assets/stylesheets/application.css
Add stylesheet link tag …
```

Fix escape double quotes on bootstrap install script

---

README.md

We are migrating our project away from sassc-rails towards cssbundling-rails with sass (and in preparation for introducing tailwind in parallel with that while we rewrite everything), however we still use administrate which as of writing [still depends on sassc-rails](https://github.com/thoughtbot/administrate/issues/2311).
At first we defined `config.assets.css_compressor = nil` by uncommenting the line in `config/environments/production.rb`, but only later realized this did not affect the test environment, which is the reason why our test suite was still failing with errors such as `ActionView::Template::Error: Error: Function rgb is missing argument $green`, and I believe other seemingly incomprensible errors such as `ActionView::Template::Error: Asset X was not declared to be …

Suggest defining config.assets.css_compressor = nil

---

lib/install/dev

There are different bin/dev being generated by cssbundling-rails and jsbundling-rails
See https://github.com/rails/jsbundling-rails/pull/174
> dev: Use an affirmative conditional
>
> ...and avoid regex in match.
>
> (Try a gem list ails vs a gem list --exact ails to see what I mean.)

Synchronize bin/dev from jsbundling-rails to cssbundling-rails

---

lib/install/bootstrap/install.rb
lib/install/bulma/install.rb
lib/install/postcss/install.rb
lib/install/sass/install.rb
lib/install/tailwind/install.rb
lib/tasks/cssbundling/install.rake

The `css:install:shared` task serves only as a prerequisite for the other installer tasks; it should not be run on its own (nor listed with `rake --tasks`).  By replacing this task with corresponding calls to Thor's `apply` method, we avoid the overhead of running `bin/rails app:template` (and `bundle install`) multiple times.
---
As a point of comparison, running the tests from #149 without this PR:
```console
$ time bundle exec appraisal rake test
real  1m3.454s
user  11m54.481s
sys   2m39.424s
```
And running them with this PR:
```console
$ time bundle exec appraisal rake test
real  0m43.129s
user  7m49.613s
sys   1m48.380s
```

Use Thor's `apply` instead of a prerequisite task

---

README.md

This PR adds documentation about omitting file extensions from `@import` statements when using cssbundling-rails with sass. See discussion in issue #92

Add instructions for including 3rd party packages in bundle

---

lib/install/bootstrap/install.rb

Fixes rails/rails#50671
Rails 7.1 included a [change][1] to allow using importmaps along with all cssbundling options. However, the Bootstrap installer was never updated to take this new default into effect (and is currently broken because of this).
This commit adds the additional configuration required to use the Bootstrap npm package with importmaps so that "rails new" generates an application that runs without errors.
[1]: https://github.com/rails/rails/commit/84458a8577e09621205f2ea86f570745033105f5

Fix running "rails new --css bootstrap" on 7.1

---

lib/tasks/cssbundling/build.rake

[PNPM](https://pnpm.io) is fairly quick / avoids some of the huge `node_module` issues associated with NPM direct usage. It also mirrors the PR for jsbundling-rails: https://github.com/rails/jsbundling-rails/pull/181

PNPM Support

---

lib/install/dev

TL;DR;
This PR fixes the problem that when a `RAILS_MASTER_KEY` is defined with the key for production in `.env` (which is the case when using Kamal for deployment), the script in `bin/dev` will start foreman which will then pick up the variables from `.env` leading to a `ActiveSupport::MessageEncryptor::InvalidMessage` error when running `bin/dev`
Kamal is added by default for new Rails apps >= v8 (see https://github.com/rails/rails/pull/51798). Although, it seems that is not fully initialized and the `.env` file generated by `kamal init` is removed when a new Rails app is generated.
-- 
There are several other problems with the `.env` approach of Kamal, so I'm not entirely sure if this PR is the "correct" fix, but is seems reasonable as `bin/dev` is only run locally to start bundling + …

Disable loading .env file when running foreman for development

---

cssbundling-rails.gemspec

By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/cssbundling-rails which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/

Provide a 'Changelog' link on rubygems.org/gems/cssbundling-rails

---

README.md

Clarify that `cssbundling-rails` isn't used if you run `rails new --css=tailwind` or `--css=saas`, rather these go to standalone `tailwindcss-rails` and `dartsaas-rails`.
You have to use `./bin/rails css:install:[tailwind|sass]` you get the `tailwind` and `Dart saas` if you want to build via `npm|yarn` and `node`.

Update README.md to clarify `rails new --css=tailwind|saas` isn't using `cssbundling-rails`

---

Gemfile.lock
lib/tasks/cssbundling/build.rake

Fix a tiny typo in the install task description.

Fix install task typo

---

Gemfile.lock
lib/install/helpers.rb
lib/tasks/cssbundling/build.rake

I'm using bun and install packages with `bun install --yarn` and its generate a yarn.lock file, same time new version of bun 1.2 generates `bun.lock` file instead of `bun.lockb`. 
Some users may have bun with `yarn.lock` file or bun with `bun.lock` 
My assets recompilation failed with:
```
RAILS_ENV=production rails assets:precompile
bin/rails aborted!
cssbundling-rails: Command install failed, ensure yarn is installed
Tasks: TOP => assets:precompile => css:build => css:install
(See full trace by running task with --trace)
```
Here is a proposal to handle this, idk what best way to do this. If this way looks ok I can fix test as well. Also we have `using_bun?` method at `Helpers` module that dose not check for `bun.lock` and return false if bun exists and yarn.lock present
- Add support …

Improve package manager detection for Bun 1.2 compatibility

---

lib/install/bulma/application.bulma.scss

This PR updates the bulma template to align with the current documentation for version 1.x. Adjustments have been made to ensure compatibility with the updated styles and components as specified in the latest version.
- By changing `@import` to `@use`, the warning below is resolved.
```sh
Deprecation Warning [import]: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import
╷
39 │ @import 'bulma/bulma';
│         ^^^^^^^^^^^^^
╵
app/assets/stylesheets/application.bulma.scss 39:9  root stylesheet
```
- I am updating the customized template based on the latest information from the official site, since the old template causes an error.
https://bulma.io/documentation/customize/with-modular-sass/

Update bulma template to match version 1.x documentation
